name: Roman Lewandowski
title: Roman Lewandowski
email: rlewando@wp.pl
description: >-
  Strona domowa Romana Lewandowskiego
baseurl: "/"
url: "http://romanlewandowski.pl"

title_separator: "|"
site.locale: pl-PL
search: false


# Build settings
markdown: kramdown
plugins: []
  # no plugins
theme: minimal-mistakes-jekyll

# Site Author
author:
  avatar: "/assets/images/roman-lewandowski2023.jpg"
  bio: |
    <ul>
      <li>55 lat, żona Danusia, 3 synów</li>
      <li>od 32 lat związany z Gminą Olsztynek i mieszczkaniec Naszego osiedla</li>
      <li> dyrektor Szpitala w Ameryce, profesor UWM</li>
      <li>radny, przewodniczący Komisji Gospodarki i Budżetu</li>
      <li>bezpartyjny</li>
    </ul>
    <p><strong><a href="/obietnicez2014">Program z poprzedniej kampanii wyborczej został zrealizowany</a></strong></p>
  email            : rlewando@wp.pl
  facebook         : roman.lewandowski.906
  linkedin         : roman-a-lewandowski-6693a7b3/
  youtube          : https://www.youtube.com/user/romanlewandowski/videos

## Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: single
      author_profile: true


exclude:
  - Gemfile
  - Gemfile.lock
