name: Roman Lewandowski
title: Roman Lewandowski
email: rlewando@wp.pl
description: >-
  Strona domowa Romana Lewandowskiego
baseurl: "/"
url: "http://romanlewandowski.pl"

title_separator: "|"
site.locale: pl-PL
search: false


# Build settings
markdown: kramdown
plugins: []
  # no plugins
theme: minimal-mistakes-jekyll

# Site Author
author:
  avatar           : "/assets/images/roman-lewandowski.jpg"
  bio              : "Bezpartyjny kandydat do Rady Miasta Olsztynka. Okręg nr 2<br /><br /> <a href=\"/obietnicez2014\">Program z poprzedniej kampanii wyborczej został zrealizowany</a>"
  email            : rlewando@wp.pl
  facebook         : roman.lewandowski.906
  linkedin         : roman-lewandowski-6693a7b3
  youtube          : https://www.youtube.com/user/romanlewandowski/videos

## Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: single
      author_profile: true


exclude:
  - Gemfile
  - Gemfile.lock
