name: Roman Lewandowski
title: Roman Lewandowski
email: rlewando@wp.pl
description: >-
  Strona domowa Romana Lewandowskiego
baseurl: "/"
url: "http://romanlewandowski.pl"

title_separator: "|"
site.locale: pl-PL
search: false


# Build settings
markdown: kramdown
plugins: []
  # no plugins
theme: minimal-mistakes-jekyll

# Site Author
author:
  avatar           : "/assets/images/roman-lewandowski2023.jpg"
  bio              : "<b>- 55 lat, żona Danusia, 3 synów,
<br> - od 32 lat związany z Gminą Olsztynek i mieszczkaniec Naszego osiedla,
<br> - dyrektor Szpitala w Ameryce, <br> profesor UWM,
<br> - radny, przewodniczący Komisji
Gospodarki i Budżetu,
<br> - bezpartyjny<b>
<br /><br /> <a href=\"/obietnicez2014\">Program z poprzedniej kampanii wyborczej został zrealizowany</a>"
  email            : rlewando@wp.pl
  facebook         : https://www.facebook.com/roman.lewandowski.906/
  linkedin         : https://www.linkedin.com/in/roman-a-lewandowski-6693a7b3/
  youtube          : https://www.youtube.com/user/romanlewandowski/videos

## Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: single
      author_profile: true


exclude:
  - Gemfile
  - Gemfile.lock
